# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paquete_principal/gui/win_buscar_libro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_buscar_libro(object):
    def setupUi(self, win_buscar_libro):
        win_buscar_libro.setObjectName("win_buscar_libro")
        win_buscar_libro.resize(468, 443)
        win_buscar_libro.setMinimumSize(QtCore.QSize(468, 0))
        win_buscar_libro.setAutoFillBackground(False)
        win_buscar_libro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_buscar_libro = QtWidgets.QTextBrowser(win_buscar_libro)
        self.text_buscar_libro.setGeometry(QtCore.QRect(80, 20, 331, 41))
        self.text_buscar_libro.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_buscar_libro.setObjectName("text_buscar_libro")
        self.radioButton_titulo = QtWidgets.QRadioButton(win_buscar_libro)
        self.radioButton_titulo.setGeometry(QtCore.QRect(190, 80, 77, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_titulo.setFont(font)
        self.radioButton_titulo.setObjectName("radioButton_titulo")
        self.radioButton_autor = QtWidgets.QRadioButton(win_buscar_libro)
        self.radioButton_autor.setGeometry(QtCore.QRect(200, 150, 72, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_autor.setFont(font)
        self.radioButton_autor.setObjectName("radioButton_autor")
        self.radioButton_categorias = QtWidgets.QRadioButton(win_buscar_libro)
        self.radioButton_categorias.setGeometry(QtCore.QRect(180, 240, 112, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_categorias.setFont(font)
        self.radioButton_categorias.setObjectName("radioButton_categorias")
        self.radioButton_lis_disponibles = QtWidgets.QRadioButton(win_buscar_libro)
        self.radioButton_lis_disponibles.setGeometry(QtCore.QRect(130, 320, 237, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_lis_disponibles.setFont(font)
        self.radioButton_lis_disponibles.setObjectName("radioButton_lis_disponibles")
        self.txtbu_titulo = QtWidgets.QTextEdit(win_buscar_libro)
        self.txtbu_titulo.setGeometry(QtCore.QRect(40, 110, 399, 31))
        self.txtbu_titulo.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.txtbu_titulo.setObjectName("txtbu_titulo")
        self.txtbu_autor = QtWidgets.QTextEdit(win_buscar_libro)
        self.txtbu_autor.setGeometry(QtCore.QRect(38, 190, 401, 31))
        self.txtbu_autor.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.txtbu_autor.setObjectName("txtbu_autor")
        self.listView_categorias = QtWidgets.QListView(win_buscar_libro)
        self.listView_categorias.setGeometry(QtCore.QRect(38, 270, 401, 31))
        self.listView_categorias.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.listView_categorias.setObjectName("listView_categorias")
        self.listView_lis_disponibles = QtWidgets.QListView(win_buscar_libro)
        self.listView_lis_disponibles.setGeometry(QtCore.QRect(38, 360, 401, 31))
        self.listView_lis_disponibles.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.listView_lis_disponibles.setObjectName("listView_lis_disponibles")

        self.retranslateUi(win_buscar_libro)
        QtCore.QMetaObject.connectSlotsByName(win_buscar_libro)

    def retranslateUi(self, win_buscar_libro):
        _translate = QtCore.QCoreApplication.translate
        win_buscar_libro.setWindowTitle(_translate("win_buscar_libro", "win_buscar_libro"))
        self.text_buscar_libro.setHtml(_translate("win_buscar_libro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Buscar libro</span></p></body></html>"))
        self.radioButton_titulo.setText(_translate("win_buscar_libro", "TITULO"))
        self.radioButton_autor.setText(_translate("win_buscar_libro", "AUTOR"))
        self.radioButton_categorias.setText(_translate("win_buscar_libro", "CATEGORIAS"))
        self.radioButton_lis_disponibles.setText(_translate("win_buscar_libro", "LISTA DE LIBROS DISPONIBLES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_buscar_libro = QtWidgets.QWidget()
    ui = Ui_win_buscar_libro()
    ui.setupUi(win_buscar_libro)
    win_buscar_libro.show()
    sys.exit(app.exec_())
