# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paquete_principal/gui/win_iniciar_sesion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_iniciar_sesion(object):
    def setupUi(self, win_iniciar_sesion):
        win_iniciar_sesion.setObjectName("win_iniciar_sesion")
        win_iniciar_sesion.resize(468, 443)
        win_iniciar_sesion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_iniciar_sesion = QtWidgets.QTextBrowser(win_iniciar_sesion)
        self.text_iniciar_sesion.setGeometry(QtCore.QRect(95, 30, 271, 41))
        self.text_iniciar_sesion.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_iniciar_sesion.setObjectName("text_iniciar_sesion")
        self.txt_nom_usuario = QtWidgets.QTextEdit(win_iniciar_sesion)
        self.txt_nom_usuario.setGeometry(QtCore.QRect(50, 160, 371, 31))
        self.txt_nom_usuario.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.txt_nom_usuario.setObjectName("txt_nom_usuario")
        self.lb_nom_usuario = QtWidgets.QLabel(win_iniciar_sesion)
        self.lb_nom_usuario.setGeometry(QtCore.QRect(50, 130, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_nom_usuario.setFont(font)
        self.lb_nom_usuario.setObjectName("lb_nom_usuario")
        self.lb_clave = QtWidgets.QLabel(win_iniciar_sesion)
        self.lb_clave.setGeometry(QtCore.QRect(50, 220, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_clave.setFont(font)
        self.lb_clave.setObjectName("lb_clave")
        self.txt_clave = QtWidgets.QTextEdit(win_iniciar_sesion)
        self.txt_clave.setGeometry(QtCore.QRect(50, 260, 371, 31))
        self.txt_clave.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.txt_clave.setObjectName("txt_clave")
        self.btn_iniciar_sesion = QtWidgets.QPushButton(win_iniciar_sesion)
        self.btn_iniciar_sesion.setGeometry(QtCore.QRect(284, 362, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_iniciar_sesion.setFont(font)
        self.btn_iniciar_sesion.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.btn_iniciar_sesion.setObjectName("btn_iniciar_sesion")

        self.retranslateUi(win_iniciar_sesion)
        QtCore.QMetaObject.connectSlotsByName(win_iniciar_sesion)

    def retranslateUi(self, win_iniciar_sesion):
        _translate = QtCore.QCoreApplication.translate
        win_iniciar_sesion.setWindowTitle(_translate("win_iniciar_sesion", "win_iniciar_sesion"))
        self.text_iniciar_sesion.setHtml(_translate("win_iniciar_sesion", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">INICIAR SESION</span></p></body></html>"))
        self.txt_nom_usuario.setHtml(_translate("win_iniciar_sesion", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lb_nom_usuario.setText(_translate("win_iniciar_sesion", "NOMBRE DE USUARIO:"))
        self.lb_clave.setText(_translate("win_iniciar_sesion", "CLAVE:"))
        self.btn_iniciar_sesion.setText(_translate("win_iniciar_sesion", "INICIAR SESION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_iniciar_sesion = QtWidgets.QWidget()
    ui = Ui_win_iniciar_sesion()
    ui.setupUi(win_iniciar_sesion)
    win_iniciar_sesion.show()
    sys.exit(app.exec_())
