# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paquete_principal/gui/win_seleccionar_libro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_seleccionar_libro(object):
    def setupUi(self, seleccionar_libro):
        seleccionar_libro.setObjectName("seleccionar_libro")
        seleccionar_libro.resize(468, 443)
        seleccionar_libro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_selecciona_libro = QtWidgets.QTextBrowser(seleccionar_libro)
        self.text_selecciona_libro.setGeometry(QtCore.QRect(110, 20, 256, 41))
        self.text_selecciona_libro.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_selecciona_libro.setObjectName("text_selecciona_libro")
        self.text_titulo = QtWidgets.QTextBrowser(seleccionar_libro)
        self.text_titulo.setGeometry(QtCore.QRect(20, 100, 181, 31))
        self.text_titulo.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_titulo.setObjectName("text_titulo")
        self.text_categoria = QtWidgets.QTextBrowser(seleccionar_libro)
        self.text_categoria.setGeometry(QtCore.QRect(20, 160, 181, 31))
        self.text_categoria.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_categoria.setObjectName("text_categoria")
        self.text_autor = QtWidgets.QTextBrowser(seleccionar_libro)
        self.text_autor.setGeometry(QtCore.QRect(20, 230, 181, 31))
        self.text_autor.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_autor.setObjectName("text_autor")
        self.text_resumen = QtWidgets.QTextBrowser(seleccionar_libro)
        self.text_resumen.setGeometry(QtCore.QRect(20, 310, 181, 111))
        self.text_resumen.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_resumen.setObjectName("text_resumen")
        self.pushButton_agregar_milist = QtWidgets.QPushButton(seleccionar_libro)
        self.pushButton_agregar_milist.setGeometry(QtCore.QRect(290, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_agregar_milist.setFont(font)
        self.pushButton_agregar_milist.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.pushButton_agregar_milist.setObjectName("pushButton_agregar_milist")
        self.text_disponibilidad = QtWidgets.QTextBrowser(seleccionar_libro)
        self.text_disponibilidad.setGeometry(QtCore.QRect(300, 280, 141, 31))
        self.text_disponibilidad.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_disponibilidad.setObjectName("text_disponibilidad")
        self.text_tiempo_entrega = QtWidgets.QTextBrowser(seleccionar_libro)
        self.text_tiempo_entrega.setGeometry(QtCore.QRect(300, 350, 131, 31))
        self.text_tiempo_entrega.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.text_tiempo_entrega.setObjectName("text_tiempo_entrega")
        self.lb_titulo = QtWidgets.QLabel(seleccionar_libro)
        self.lb_titulo.setGeometry(QtCore.QRect(40, 80, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_titulo.setFont(font)
        self.lb_titulo.setObjectName("lb_titulo")
        self.lb_categoria = QtWidgets.QLabel(seleccionar_libro)
        self.lb_categoria.setGeometry(QtCore.QRect(20, 140, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_categoria.setFont(font)
        self.lb_categoria.setObjectName("lb_categoria")
        self.lb_autor = QtWidgets.QLabel(seleccionar_libro)
        self.lb_autor.setGeometry(QtCore.QRect(30, 210, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_autor.setFont(font)
        self.lb_autor.setObjectName("lb_autor")
        self.lb_resumen = QtWidgets.QLabel(seleccionar_libro)
        self.lb_resumen.setGeometry(QtCore.QRect(30, 280, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_resumen.setFont(font)
        self.lb_resumen.setObjectName("lb_resumen")
        self.lb_disponibilidad = QtWidgets.QLabel(seleccionar_libro)
        self.lb_disponibilidad.setGeometry(QtCore.QRect(300, 260, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lb_disponibilidad.setFont(font)
        self.lb_disponibilidad.setObjectName("lb_disponibilidad")
        self.lb_tiempo_entrega = QtWidgets.QLabel(seleccionar_libro)
        self.lb_tiempo_entrega.setGeometry(QtCore.QRect(300, 330, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lb_tiempo_entrega.setFont(font)
        self.lb_tiempo_entrega.setObjectName("lb_tiempo_entrega")
        self.graphicsView_img = QtWidgets.QGraphicsView(seleccionar_libro)
        self.graphicsView_img.setGeometry(QtCore.QRect(290, 90, 151, 91))
        self.graphicsView_img.setStyleSheet("background-color:rgb(190, 249, 255)\n"
"")
        self.graphicsView_img.setObjectName("graphicsView_img")

        self.retranslateUi(seleccionar_libro)
        QtCore.QMetaObject.connectSlotsByName(seleccionar_libro)

    def retranslateUi(self, seleccionar_libro):
        _translate = QtCore.QCoreApplication.translate
        seleccionar_libro.setWindowTitle(_translate("seleccionar_libro", "win_seleccionar_libro"))
        self.text_selecciona_libro.setHtml(_translate("seleccionar_libro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">SECCION DE LIBROS</span></p></body></html>"))
        self.pushButton_agregar_milist.setText(_translate("seleccionar_libro", "AGREGAR A MI LISTA"))
        self.lb_titulo.setText(_translate("seleccionar_libro", "TITULO:"))
        self.lb_categoria.setText(_translate("seleccionar_libro", "CATEGORIA:"))
        self.lb_autor.setText(_translate("seleccionar_libro", "AUTOR:"))
        self.lb_resumen.setText(_translate("seleccionar_libro", "RESEÑA:"))
        self.lb_disponibilidad.setText(_translate("seleccionar_libro", "DISPONIBILIDAD:"))
        self.lb_tiempo_entrega.setText(_translate("seleccionar_libro", "TIEMPO DE ENTREGA:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    seleccionar_libro = QtWidgets.QWidget()
    ui = Ui_seleccionar_libro()
    ui.setupUi(seleccionar_libro)
    seleccionar_libro.show()
    sys.exit(app.exec_())
